version: '3.8'

services:
  ocservreportsapi:
    build: .
    container_name: ocservreportsapi
    restart: always
    volumes:
      - ${W_DIR}:/data/
    environment:
      - TOKEN=${TG_TOKEN}
      - CHAT_ID=${TG_CHAT_ID}
      - DIRECTORY=/data

